### ISSUE TITLE
Xrechnung UBL 2.1 CreditNote gives possibly wrong warning when validated with validationtool-1.3.0/validator-configuration-xrechnung_2.0.0_2020-07-31

### ISSUE THREAD

**Issue by Roman-it20one** [itplr-kosit/validator-configuration-xrechnung#55] opened 2020-12-28 11:13 UTC
Hi Dev Team,

when testing an UBL2.1 Xrechnung CreditNote with the following configuration:

validationtool-1.3.0
validator-configuration-xrechnung_2.0.0_2020-07-31

we get the warning:

[BR-DE-21] Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.

The value in question looks like this in our document:

<cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0</cbc:CustomizationID>

The validator acutally wont even recognize the document if we insert anything else here. But the schema seems to check for xrechnung_1.2 and throws a warning if it does not find that value here. This doesn't seem to make sense.

Kind regards
Roman Gundacker
it20one e-invoicing GmbH

**Comment by phax** [comment] 2020-12-28 16:52
This is a duplicate of https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/45 I assume. Check out the 2.0.1 release

**Comment by rkottmann** [comment] 2020-12-30 12:19
Yes, this was a bug. Please migrate to new version or fix the `<match>` Element in the scenario.xml for the CreditNote scenario yourself.

**Closed by rkottmann** 2020-12-30 12:19 UTC
